### ISSUE TITLE
AutoInjector breaks when calling .new and the parameters have generics

### ISSUE THREAD

**Issue by luanbatistadev** [Flutterando/auto_injector#10]
# Describe the bug
When we use auto_injector .new it breaks in types that have generics, such as Map<String, dynamic>

# Environment
Add your flutter doctor -v

[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-arm64, locale en-BR)
    • Flutter version 3.13.0 on channel stable at /Users/luanrafaelbatistaramos/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/luanrafaelbatistaramos/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio TIMWE.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.96
• No issues found!
# Add your pubspec.yaml

name: cimed
description: Cimed - Portal dos Representantes
publish_to: "none"

version: 17.2.0+112
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter_icons:
  image_path_android: "lib/assets/images/logo.png"
  image_path_ios: "lib/assets/images/logo.png"
  android: true
  ios: true

dependencies:
  animate_do: ^3.0.2
  auto_injector:
  bloc: ^8.1.2
  brasil_fields: ^1.14.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.5
  collection: ^1.17.2
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  detectable_text_field: ^2.1.0
  dio: ^5.3.2
  document_file_save_plus: ^2.0.0
  encrypt: ^5.0.1
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  extended_masked_text: ^2.3.1
  file_picker: ^5.3.3
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_bloc: ^8.1.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.0.4+1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  hive: ^2.2.3
  horizontal_data_table: ^4.3.1
  http: ^1.1.0
  image_picker: ^1.0.2
  in_app_update: ^4.1.4
  intl: ^0.18.1
  jiffy: ^6.2.1
  jwt_decoder: ^2.0.1
  line_icons: ^2.0.3
  mask_text_input_formatter: ^2.5.0
  new_version_plus: ^0.0.11
  open_filex: ^4.3.2
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  percent_indicator: ^4.2.3
  pinch_zoom_image_last: ^0.4.1 #Discontinuado
  pretty_dio_logger: ^1.3.1
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform
  rx_notifier: ^2.3.0
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  skeleton_animation: ^0.1.4
  snack: ^2.0.0
  sp_util: ^2.0.3
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  workmanager: ^0.5.1

dependency_overrides:
  auto_injector:
    path: ../flutterando/auto_injector

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/json/
    - assets/images/
    - assets/version.txt

# To Reproduce

class TestComplexNamed {
  final Map<String, dynamic>? value;
  final Map<String, List<Map<String, dynamic>>>? map;

  TestComplexNamed({this.value, this.map});
}

TestComplexNamed.new

# Expected behavior

Should find exactly bind

# Screenshots
![Screenshot 2023-08-22 at 13 31 07](https://github.com/Flutterando/auto_injector/assets/56078396/46d40857-8cde-4ea3-a056-20aadf1aa3ab)
![Screenshot 2023-08-22 at 13 31 48](https://github.com/Flutterando/auto_injector/assets/56078396/e618b8ab-6e91-4be0-8ddf-ea008ad01d4e)
![Screenshot 2023-08-22 at 13 32 32](https://github.com/Flutterando/auto_injector/assets/56078396/daa463e8-de30-4afb-955d-18bd0e5a6314)

**Comment by davidsdearaujo** [comment]
Fixed on #11
